---
- hosts: all
  become: true
  tasks:
    - name: Download Google Chrome RPM package
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        dest: /tmp/google-chrome-stable_current_x86_64.rpm
        mode: '0644'

    - name: Install Google Chrome
      zypper:
        name: /tmp/google-chrome-stable_current_x86_64.rpm
        state: present
        disable_gpg_check: yes

    - name: Clean up Chrome RPM package
      file:
        path: /tmp/google-chrome-stable_current_x86_64.rpm
        state: absent
